/* ADAM/DS — src/components/Icon/gem-icons.js · gem & facet family */
// [plan:2026-09-28_000000-lump-sum-builds.md#phase-1] · Diamonds, Sparkles, Facets, Rewards.
import {
  Diamond,
  DiamondsFour,
  WarningDiamond,
  Sparkle,
  Star,
  StarFour,
  ShootingStar,
  Hexagon,
  Octagon,
  WarningOctagon,
  Cube,
  CubeFocus,
  CubeTransparent,
  Crown,
  CrownSimple,
  CrownCross,
  Trophy,
  Medal,
  MedalMilitary,
} from "@phosphor-icons/react";

// — Gem map — Pascal + kebab aliases so <Icon name="diamonds-four" /> works.
export const GEM_MAP = {
  Diamond,
  "diamond": Diamond,
  DiamondsFour,
  "diamonds-four": DiamondsFour,
  WarningDiamond,
  "warning-diamond": WarningDiamond,
  Sparkle,
  "sparkle": Sparkle,
  Star,
  "star": Star,
  StarFour,
  "star-four": StarFour,
  ShootingStar,
  "shooting-star": ShootingStar,
  Hexagon,
  "hexagon": Hexagon,
  Octagon,
  "octagon": Octagon,
  WarningOctagon,
  "warning-octagon": WarningOctagon,
  Cube,
  "cube": Cube,
  CubeFocus,
  "cube-focus": CubeFocus,
  CubeTransparent,
  "cube-transparent": CubeTransparent,
  Crown,
  "crown": Crown,
  CrownSimple,
  "crown-simple": CrownSimple,
  CrownCross,
  "crown-cross": CrownCross,
  Trophy,
  "trophy": Trophy,
  Medal,
  "medal": Medal,
  MedalMilitary,
  "medal-military": MedalMilitary,
};

// — Kebab list for the playground + docs.
export const GEM_NAMES = [
  "diamond",
  "diamonds-four",
  "warning-diamond",
  "sparkle",
  "star",
  "star-four",
  "shooting-star",
  "hexagon",
  "octagon",
  "warning-octagon",
  "cube",
  "cube-focus",
  "cube-transparent",
  "crown",
  "crown-simple",
  "crown-cross",
  "trophy",
  "medal",
  "medal-military",
];
